name: Test

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          MC_USERNAME: ${{secrets.MC_USERNAME}}
          MC_PASSWORD: ${{secrets.MC_PASSWORD}}
